#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t infamous"

$L "    ___            __ ";
$L " / (_  _ /|/|     (   ";
$L "(/)/  (//   |()(/__)  ";
                      
$L "Welcome to Android `getprop ro.build.version.release` / Infamous-`getprop ro.infamous.version`";
