add_lunch_combo infamous_dlx-userdebug
add_lunch_combo infamous_hltetmo-userdebug
add_lunch_combo infamous_maguro-userdebug
add_lunch_combo infamous_grouper-userdebug
add_lunch_combo infamous_shamu-userdebug
add_lunch_combo infamous_trltetmo-userdebug
